# Generated by Django 4.2.21 on 2026-05-25 07:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('presenting_concerns', models.TextField(blank=True)),
                ('interventions', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_note', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='patients.patient')),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('min_score', models.PositiveSmallIntegerField(default=0)),
                ('max_score', models.PositiveSmallIntegerField(default=10)),
                ('alert_threshold', models.PositiveSmallIntegerField(default=7)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Relative importance used by the composite scoring algorithm.', max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10)])),
                ('direction', models.CharField(choices=[('higher_is_better', 'Higher is better'), ('lower_is_better', 'Lower is better')], default='higher_is_better', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.CharField(blank=True, max_length=240)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_entries', to='notes.scoringcriterion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='notes.sessionnote')),
            ],
            options={
                'ordering': ['criterion__name'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionnote',
            index=models.Index(fields=['patient', 'session_date'], name='notes_sessi_patient_d0e329_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scoringcriterion',
            unique_together={('therapist', 'name')},
        ),
        migrations.AddIndex(
            model_name='scoreentry',
            index=models.Index(fields=['criterion', 'value'], name='notes_score_criteri_18f0d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scoreentry',
            unique_together={('session', 'criterion')},
        ),
    ]
