# Generated by Django 4.2.21 on 2026-05-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='scheduled', max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('reminder_email', models.BooleanField(default=False)),
                ('reminder_sms', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['starts_at', 'status'], name='appointment_starts__1f6bcd_idx'), models.Index(fields=['patient', 'starts_at'], name='appointment_patient_c89bba_idx')],
            },
        ),
    ]
