# Generated by Django 4.2.21 on 2026-05-01 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='scheduled', max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('reminder_email', models.BooleanField(default=False)),
                ('reminder_sms', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=160)),
                ('medical_history', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('presenting_concerns', models.TextField(blank=True)),
                ('interventions', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_note', to='crm.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='crm.patient')),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('min_score', models.PositiveSmallIntegerField(default=0)),
                ('max_score', models.PositiveSmallIntegerField(default=10)),
                ('alert_threshold', models.PositiveSmallIntegerField(default=7)),
                ('direction', models.CharField(choices=[('higher_is_better', 'Higher is better'), ('lower_is_better', 'Lower is better')], default='higher_is_better', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.CharField(blank=True, max_length=240)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_entries', to='crm.scoringcriterion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='crm.sessionnote')),
            ],
            options={
                'ordering': ['criterion__name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='crm.patient'),
        ),
        migrations.AddIndex(
            model_name='sessionnote',
            index=models.Index(fields=['patient', 'session_date'], name='crm_session_patient_c31be7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scoringcriterion',
            unique_together={('therapist', 'name')},
        ),
        migrations.AddIndex(
            model_name='scoreentry',
            index=models.Index(fields=['criterion', 'value'], name='crm_scoreen_criteri_7fe453_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scoreentry',
            unique_together={('session', 'criterion')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['therapist', 'last_name'], name='crm_patient_therapi_634839_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['therapist', 'is_active'], name='crm_patient_therapi_5c55cf_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['starts_at', 'status'], name='crm_appoint_starts__e6dbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'starts_at'], name='crm_appoint_patient_4e2cff_idx'),
        ),
    ]
