# Generated by Django 4.2.30 on 2026-05-01 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringcriterion',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Relative importance used by the composite scoring algorithm.', max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
