# Generated by Django 4.2.21 on 2026-05-25 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('national_id', models.CharField(blank=True, help_text='Government-issued ID or passport number. Used to prevent duplicate records.', max_length=50, verbose_name='National ID / Passport No.')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('other', 'Other')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=80)),
                ('occupation', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=160)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=80)),
                ('emergency_contact_phone1', models.CharField(blank=True, max_length=40)),
                ('emergency_contact_phone2', models.CharField(blank=True, max_length=40)),
                ('previous_treatment', models.TextField(blank=True)),
                ('current_medication', models.TextField(blank=True)),
                ('ok_to_leave_message', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('ok_to_contact_by_email', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], max_length=5)),
                ('referral_source', models.CharField(blank=True, choices=[('self', 'No one (Self Referral)'), ('friend', 'Friend'), ('family', 'Family Member'), ('partner', 'Partner')], max_length=7)),
                ('used_counselling_before', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('booking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('intake_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('client_signed_date', models.DateField(blank=True, null=True)),
                ('counsellor_signed_date', models.DateField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['therapist', 'last_name'], name='patients_pa_therapi_25d419_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['therapist', 'is_active'], name='patients_pa_therapi_f1280d_idx'),
        ),
    ]
